// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { setRecoveryActive } from '@/lib/recoveryState';

const rawUrl = import.meta.env.VITE_SUPABASE_URL;
const rawKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const SUPABASE_URL = typeof rawUrl === 'string' ? rawUrl.replace(/^["']|["']$/g, '').trim() : '';
export const SUPABASE_PUBLISHABLE_KEY = typeof rawKey === 'string' ? rawKey.replace(/^["']|["']$/g, '').trim() : '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});

// Immediately register auth event listener so PASSWORD_RECOVERY is never missed
supabase.auth.onAuthStateChange((event, session) => {
  try {
    console.info(`[auth-recovery] Supabase auth event: ${event}`, {
      userId: session?.user?.id,
      email: session?.user?.email,
      hasSession: Boolean(session),
    });
  } catch {}

  if (event === 'PASSWORD_RECOVERY') {
    console.info('[auth-recovery] Detected PASSWORD_RECOVERY event, locking to reset password flow');
    setRecoveryActive(true);
  }
});
